services:
  - name: Devolio
    type: web
    env: docker
    repo: https://github.com/lissy93/devolio.git
    plan: starter
    branch: master
    numInstances: 1
    # healthCheckPath: /app/health-check
    envVars:
      - key: GITHUB_TOKEN
        value: ''
      - key: TWITTER_TOKEN
        value: ''
